server:
  port: 9091
spring:
  application:
    name: CURRENCY-CONVERSION-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
#Database Setup H2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:/practice/H2database/currency
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
